[package]
name = "smidr"
version = "0.3.0"
edition = "2024"
authors = ["Max-Mend"]
description = "Smidr is a cargo-inspired build tool for C projects, meant to bridge dependencies across different build systems into a single build."
license = "MIT OR Apache-2.0"
repository = "https://github.com/Max-Mend/smidr"
readme = "README.md"
keywords = ["c", "build-tool", "cli", "compiler", "build-system"]
categories = ["development-tools", "command-line-utilities"]

[dependencies]
ariadne = "0.6.0"
clap = { version = "4.6.6", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0.20"
toml = "0.8"
